name: Test Telegram

on:
  workflow_dispatch: {}   # bisa dijalankan manual dari tab Actions

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send test message
        env:
          TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          TEXT="✅ Test ping dari GitHub Actions (${{ github.repository }})"
          curl -sS -X POST "https://api.telegram.org/bot${TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            -d parse_mode="Markdown" \
            --data-urlencode "text=${TEXT}"
